### ISSUE TITLE
I cannot use the same key to express two different parameters

### ISSUE THREAD

**Issue by mmussio85** [mwpowellhtx/NDesk.Options.Extensions#3]
I've found this library very useful but I'm having an issue right now. I would like to add something like this: var p = new OptionSet() { { "input|input:", "The file with the results", v => { resultsFileName = v; } }, { "h|help", "Show this help", v => { isHelp = (v != null); } } };

because for two different commands input is a numeric entry and for other command is a boolean parameter. But unfortunatelly, I'm getting an error {"An item with the same key has already been added."} So, I guess the library is using an internal Dictionary.

How can I solve this issue, If I can...

Thanks Marcos

**Comment by mwpowellhtx** [comment]
I'm pretty sure that's by design, but is beyond the scope of the extensions. As you guessed [Options](http://github.com/gibbed/NDesk.Options/search?utf8=%E2%9C%93&q=dictionary) is using a Dictionary underneath.

Also, I'm not sure who's maintaining the ``Options`` package distribution, however.

If you decide on a migration path for ``Options``, do let me know. I'll be happy to stay in sync with which ever is most current.

One observation, is ``"input|input:"`` intentional? I'm not sure how [NDesk.Options](http://www.nuget.org/packages/NDesk.Options/) treats punctuation, but might be an interesting test case to add to his [library](http://github.com/gibbed/NDesk.Options). That may cause a potential duplication. Without seeing your exceptions or stack trace, it's hard to say.

Let me know.

**Comment by mmussio85** [comment]
Actually Ndesk is supporting ":" as a separator caracter. The stacktrace is this one:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at NDesk.Options.OptionSet.AddImpl(Option option)
   at NDesk.Options.OptionSet.InsertItem(Int32 index, Option item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at NDesk.Options.OptionSet.Add(String prototype, String description, Action`1 action)
   at Parser.Program.Main(String[] args) in c:\users\marcos\documents\visual studio 2015\Projects\Parser\Parser\Program.cs:line 17
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


I think I should go for another option because It seems that repeated keys are not supported by NDesk core

**Comment by mwpowellhtx** [comment]
Good to know re: punctuation. Assuming that's the case, then don't you think ``"input|input"`` would yield a duplicate? Suggest ``"i|input"``, or something along those lines to avoid duplication.
